version: '3.1'

services:

  db:
    image: postgres:latest
    #image: postgres #use latest image
    ports:
     - 5432:5432 #enable external ports
    restart: always
    environment:
     - POSTGRES_PASSWORD=solid_passwd #superuser password
     - POSTGRES_USER=gas_user #superuser name
     - POSTGRES_DB=liquid_database
    volumes: 
     - liquid_database_data:/var/lib/postgresql/data #persist data even if container shuts down

volumes:
  liquid_database_data:
